<?php

/**
 * Photo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Photo extends BasePhoto
{
    function init($titre, $sousTitre, $description, $idSerie, $idTag, $img_src){
        $this->Label = $titre;
        $this->Extension = $sousTitre;
        $this->Description = $description;
        $this->IdSerie = $idSerie;
        $this->IdTag = $idTag;
        $this->Fichier = $img_src;
        
    }
}