#Serie:
Serie:
  tableName: Serie
  actAs:
    Timestampable: 
      created:
        name: Add_date
      updated:
        name: Mod_date
    Searchable:
      fields: [id,Label]
  columns:
    Label:
      type: string(255)
    Description:
      type: string(8000)
      
#Tag:
Tag:
  tableName: Tag
  actAs:
    Timestampable: 
      created:
        name: Add_date
      updated:
        name: Mod_date
    Searchable:
      fields: [id,Label,IdSerie]
  columns:
    Label:
      type: string(255)
    Description:
      type: string(8000)
    IdSerie:
      type: integer
  relations:
    serie:
      class: Serie
      local: IdSerie
      foreign: id
      onDelete: SET NULL
      alias: Serie # on pourra acceder à l'objet avec User->Contact
      foreignAlias: Tags
      
#Photo:
Photo:
  tableName: Photo
  actAs:
    Timestampable: 
      created:
        name: Add_date
      updated:
        name: Mod_date
    Searchable:
      fields: [id,Label,IdSerie,IdTag]
  columns:
    Label:
      type: string(255)
    Fichier:
      type: string(255)
    Extension:
      type: string(255)
    Description:
      type: string(255)   
    IdSerie:
      type: integer
    IdTag:
      type: integer
  relations:
    serie:
      class: Serie
      local: IdSerie
      foreign: id
      onDelete: SET NULL
      alias: Serie # on pourra acceder à l'objet avec User->Contact
      foreignAlias: Series
    tag:
      class: Tag
      local: IdTag
      foreign: id
      onDelete: SET NULL
      alias: Tag # on pourra acceder à l'objet avec User->Contact
      foreignAlias: Tags
      